title: TimeFracture
email: info@timefracturetechno.com
description: >-
  Trance and Techno enthusiast & Acid techno producer. Message me for collaborations or DJ events.
baseurl: ""
url: "https://timefracturetechno.com"

socials:
  soundcloud:
    title: TimeFracture
    href: "https://soundcloud.com/timefracture"
    fa-icon: fa-brands fa-soundcloud fa-2xl

  instagram:
    title: TimeFracture
    href: "https://www.instagram.com/timefracture.techno"
    fa-icon: fa-brands fa-instagram fa-2xl

releases:
  - name: Give me acid techno
    image: /assets/images/releases/give-me-acid-techno.jpeg
    url: https://soundcloud.com/timefracture/give-me-acid-techno

  - name: Lost inside the noise
    image: /assets/images/releases/lost-inside-the-noise.jpeg
    url: https://soundcloud.com/timefracture/lost-inside-the-noise

  - name: Wicked Generation
    image: /assets/images/releases/wicked-generation.jpeg
    url: https://soundcloud.com/timefracture/wicked-generation

exclude:
  - docker-compose.yml
