services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --force_polling --drafts
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
